server:
  port: 8080

spring:
  main:
    web-application-type: reactive

  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: http://user-service:8085
          predicates:
            - Path=/api/users/**
        - id: product-service
          uri: http://product-service:8082
          predicates:
            - Path=/api/products/**
