spring:
  datasource:
    url: jdbc:mysql://mysql:3306/auth_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: redis
      port: 6379
jwt:
  secret: my_super_secret_key_that_is_long_enough_and_secure
  expiration: 86400000
server:
  port: 8081