version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: auth-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: auth_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_auth_data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:7.2
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - backend

  config-server:
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/config-repo
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH-LOCATIONS=file:/config-repo
    networks:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8888/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  mysql_auth_data:

networks:
  backend:
    driver: bridge
    name: backend
