spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://config-server:8888

  profiles:
    active: docker

  cloud:
    config:
      uri: http://config-server:8888

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG
    reactor.netty.http.client: DEBUG
