version: "3.9"
services:
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      config-server:
        condition: service_healthy
      mysql:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend

networks:
  backend:
    external: true